### ISSUE TITLE
[Feature] - allow to setup the mariadb minimun db size through Helm

### ISSUE THREAD

**Issue by seb-835** [vultr/slik#26]
For debug purpose,
having a requested maria db size of 45go is a big to much, 
please give us the opportunity to fix it through helm and not hard-code it in go code ;)

**Comment by happytreees** [comment]
https://github.com/vultr/slik/blob/a666d466a60bb2126d3cde2cb2f1e4ed2a93646f/pkg/reconciler/reconciler.go#L203

**Comment by happytreees** [comment]
Hello @seb-835 ! 

Thank you for the submission! During our testing we found that 45GB is a hard requirement for MariaDB in this application so that is why the limit is enforced via code. 

At this time we do are not planning to reduce this floor.
